# Generated by Django 4.1.2 on 2022-12-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_spaces', models.IntegerField()),
                ('parking_type', models.CharField(choices=[('BOLLARD', 'Bollard'), ('CORRAL', 'Corral'), ('DECORATIVE', 'Decorative'), ('GARAGE', 'Garage'), ('GRID', 'Grid'), ('HANDRAIL', 'Handrail'), ('HANGER', 'Hanger'), ('INNOVATIVE', 'Innovative'), ('LID', 'Lid'), ('LOCKER', 'Locker'), ('MINIMAL_FRONT', 'Minimal_front'), ('STAPLE', 'Staple'), ('WAVE', 'Wave'), ('PUMP_STATION', 'Pump Station'), ('REPAIR_STATION', 'Repair Station'), ('TREE', 'Tree'), ('RENTAL_STATION', 'Rental Station')], max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
